### ISSUE TITLE
Not retrieving the Kirundi bible

### ISSUE THREAD

**Issue by schammahmuhizi** [martijnlentink/propresenter-custom-bibles#16]
Thank you for sharing this incredible work, i was looking for that script for so long, but i got an issue for my side, i needed to add a Kirundi Language Bible, but it seems like not working at all, i tried to run the .exe but it close the terminal after entering the three letters language code which is "**RUN1967**", i also used to bible_import.py in order to check what is going wrong, then it gives the error below: 

Traceback (most recent call last):
  File "C:\Users\Schammah\Downloads\propresenter-custom-bibles-2024-03-05\propresenter-custom-bibles-2024-03-05\bible_import.py", line 328, in <module>
    available_bibles = retrieve_bibles_for_language(language)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Schammah\Downloads\propresenter-custom-bibles-2024-03-05\propresenter-custom-bibles-2024-03-05\bible_import.py", line 46, in retrieve_bibles_for_language
    available_bibles = { x['id']:x for x in bible_list_json["response"]["data"]["versions"]}
                                            ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'response'

Thank you again for your precious work, i'm looking for your help

**Comment by schammahmuhizi** [comment]
Thank you, I solved the problem, it was the three letter language code that was the problem, but after reading https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes on  wikipedia link about code for languages, i found that proper language code for my language, 

Thank you again for this incredible work
