### ISSUE TITLE
Doesn't work on Mac that has Intel processor

### ISSUE THREAD

**Issue by Hookist** [martijnlentink/propresenter-custom-bibles#19]
In church I have Mac that works on Intel processor. When I've tried to run the program it shows me "bad cpu type in executable".
Then I came to my brother he has two Macs.
Program on Mac with apple processor works perfect but on the seond Max that Intel processor has the same issue "bad cpu type in executable".
Is it possible to make specific built that will work on Mac with old arcitecture of processor?

**Comment by martijnlentink** [comment]
I'll see what I can do. Maybe if I change the VM type in the pipeline works, I don't have an old Mac lying around to test though, so if it is okay with you that I ask you to test on the machine, that will help me massively.

**Comment by Hookist** [comment]
Sure! I can test

**Comment by Hookist** [comment]
“bible_import” is damaged and can’t be opened. You should move it to the Bin.

![image](https://github.com/martijnlentink/propresenter-custom-bibles/assets/18694597/e5bed443-dd18-472d-aac5-7cbe61d6a84d)

**Comment by martijnlentink** [comment]
Okay. Next attempt 😄 
[bible_import.OSX.x86_64.tar.zip](https://github.com/martijnlentink/propresenter-custom-bibles/files/15254544/bible_import.OSX.x86_64.tar.zip)

**Comment by Hookist** [comment]
Unfortunatelly same error 😬

**Comment by martijnlentink** [comment]
Sorry I haven't had the time to work on this further past days. That is indeed possible!

The bible should be stored as an RVBIBLE file in `%programdata%\RenewedVision\ProPresenter\Bibles\sideload`.
And you should copy it on your Mac to location `/Library/Application Support/RenewedVision/RVBibles/v2/``

Hopefully this helps you.

**Comment by Architeh** [comment]
i got to this stage: "Last login: Wed Nov 6 14:48:22 on ttys000
/Users/media/Downloads/bible_import ; exit;
media@Mac-Pro-media ~ % /Users/media/Downloads/bible_import ; exit;
Which language would you like to download?
Please give in a valid ISO 639 three character language code: ukr
3786: BIBLE Modern translation (CUV)
186: Bible in trans. Ivan Ohienko 1962 (UBIO)
188: Bible in translation P. Kulish and I. Pulyu, 1905 (UKRK)
204: The Holy Bible: In Modern Language (UMT)
3269: New Ukrainian Translation (NPU)
3149: Translation. Yu. Popchenko. (NUP)
1755: Translation by R. Turkonyak (UTT)
Please select the number above to download the scripture: 1755
Retrieve bible metadata
It appears that there is already a download folder for bible UTT. Are you sure you want to download the bible contents? [y/N]: y
Starting download Translation by R. Turkonyak
Traceback (most recent call last):
 File "bible_import.py", line 362, in <module>
 File "bible_import.py", line 83, in download_bible_chapters
KeyError: 'offline'
[2632] Failed to execute script 'bible_import' due to unhandled exception!" how to fix it?

**Comment by saradoann-vntg** [comment]
> Sorry I haven't had the time to work on this further past days. That is indeed possible!
> 
> The bible should be stored as an RVBIBLE file in `%programdata%\RenewedVision\ProPresenter\Bibles\sideload`. And you should copy it on your Mac to location `/Library/Application Support/RenewedVision/RVBibles/v2/`
> 
> Hopefully this helps you.

Thank you so much! Our church has faced this problem for a long time and now we have been able to solve it because of your work! Thousands thanks to you!

**Comment by begrafx** [comment]
Watching this thread. I just tried it on my i5 MacMini, and I too get the "bad CPU type in executable" message. 

The file I used was from the zip "bible_import.OSX.tar.zip".

**Comment by martijnlentink** [comment]
A new test for building using universal arch type
[bible_import.OSX.tar.zip](https://github.com/user-attachments/files/21087415/bible_import.OSX.tar.zip)

**Comment by rebelojose** [comment]
yes it worked in Macbook intel, but don't copy to Props, probably because is not compatible with version 19, I 'm in version 19

**Comment by saradoann-vntg** [comment]
oh wow, it actually worked this time — tysm for the awesome work, man! 🙌

**Comment by martijnlentink** [comment]
Great to hear! I'll promote them as latest release for everyone to use and enjoy!

**Comment by rebelojose** [comment]
I find where is .rvbibles stored on macOX after downloaded w/ bible_import, is in `/myuser*/output` and after is only need *.rvbibles move to `/Library/Application Support/RenewedVision/RVBibles/v2/ and now it is working` . 

tks for this script @martijnlentink , very useful 💯 :-)``

**Comment by martijnlentink** [comment]
> I find where is .rvbibles stored on macOX after downloaded w/ bible_import, is in `/myuser*/output` and after is only need *.rvbibles move to `/Library/Application Support/RenewedVision/RVBibles/v2/ and now it is working` .
> 
> tks for this script [@martijnlentink](https://github.com/martijnlentink) , very useful 💯 :-)``

Interesting, My guess is that it didn't have enough permissions to copy that file to that location when running. Great that you were able to fix it my manually moving the file!

**Comment by martijnlentink** [comment]
Resolved in latest release 🎉
