### ISSUE TITLE
[BUG] Propresenter Crash when Searching Scripture

### ISSUE THREAD

**Issue by macsamsonx** [martijnlentink/propresenter-custom-bibles#38]
I've got this error, when I try to search a scripture

Using Windows 11 -

System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ProPresenter.DO.Bibles.BibleHelper.MatchBook(BibleBase bible, String bookName)
   at ProPresenter.DO.Bibles.BibleHelper.ParseReferenceText(BibleBase bible, String text, BibleReference& startReference, BibleReference& endReference)
   at ProPresenter.ViewModels.BibleVM.UpdatePresentationContent(BibleBase bible, Boolean skipUndos)
   at ProPresenter.ViewModels.BibleVM.<.ctor>b__209_3(Object s, EventArgs e)
   at System.Windows.Threading.DispatcherTimer.FireTick(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at ProPresenter.Entry.Run(String[] args, InstanceValidator instanceValidator, SharedData`1 sharedData)
   at ProPresenter.Entry.Main(String[] args)

**Comment by martijnlentink** [comment]
Hi there,

Could you provide me with some more information like what search query did you use and which translation?

**Comment by macsamsonx** [comment]
Ohh. I did't expect to get fast response. Thank you brother!

"1a30ba73-9f0d-41ed-84f8-227439c6de34|SWE|Magandang Balita Biblia (2005)|1"];

MMB05 is Filipino Bible -> I swap it with SWE

**Comment by martijnlentink** [comment]
Okay. And to clarify. You get this error message upon opening the bible, clicking the scripture dropdown or using the search box?
![image](https://github.com/user-attachments/assets/935c7a8d-ad76-4087-8256-dd9b7c595ef0)

**Comment by macsamsonx** [comment]
Yes Sir! After I click the specific verse

**Comment by macsamsonx** [comment]
Im just trying out so I just tried for one translation.

Did I did something wrong in the installation

I run the phyton script
-> Select a language
-> Select Translation
-> Hit OK
-> Choose a free version to swap that was not yet installed to my propresenter
-> Restart ProPresenter

**Comment by macsamsonx** [comment]
Yes any verse and title

**Comment by macsamsonx** [comment]
I tried with the OLD version of Filipino Bible it works with [Ang Salita ng Diyos (SND)](https://www.biblegateway.com/versions/Ang-Salita-ng-Diyos-SND/)

**Comment by martijnlentink** [comment]
Fixed issue in my last commit. Will be fixed in next release

**Comment by martijnlentink** [comment]
Newest release now out! [Click here to download](https://github.com/martijnlentink/propresenter-custom-bibles/releases/tag/2025-01-02). Keen to hear if this fixes the issue!
